### ISSUE TITLE
> char in filename stopping jeykll from running

### ISSUE THREAD

**Issue by pouretrebelle** [mirobot/apps.mirobot.io#7]
The `list->sentence.png` and `sentence->list.png` in `assets/apps/snap/help` caused an rb_sysopen error when running `jekyll serve` on Windows. I removed the > from the filenames and it worked fine.

**Comment by bjpirt** [comment]
Looks like these files weren't needed anyway so I've removed them and a bunch of other things in 9bfbc72e7fdaef405075d32d1c5a4c8f4638bc90 that help slim down the size a bit. It was also causing issues with the Chrome App on Windows. Thanks for reporting it, it helped me track down the Chrome App issue.
